---
author: "Darlan Conterno Minussi"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: bookdown::gitbook
editor_options: 
  chunk_output_type: console
---
# Tumors

```{r setup_tumors, message=FALSE, warning=FALSE, echo=FALSE}
source("R/setup.R")
source("R/run_umap.R")
source("R/run_clustering.R")
source("R/order_dataset.R")
source("R/plot_umap.R")
source("R/calculate_consensus.R")
source("R/consensus_genomic_classes.R")
source("R/run_me_tree.R")
source("R/plot_heatmap.R")
source("R/plot_consensus_heatmap.R")
source("R/gain_loss_percentage.R")
source("R/calc_genclass_length.R")
```

```{r theme_setup}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Thu Mar  4 14:23:11 2021
# ggplot theme setup
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Thu Mar  4 14:23:17 2021

my_theme <- list(
  ggplot2::theme(
    axis.title.x = element_text(colour = "black", size = 16),
    axis.text.x = element_text(size = 14),
    axis.title.y = element_text(colour = "black", size = 16),
    axis.text.y = element_text(size = 14),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 14)
  )
)
```


## TN1
```{r TN1}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN1_ploidy <- 3.45

TN1_popseg <- readRDS(here("extdata/popseg/TN1_popseg.rds"))

TN1_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN1_popseg_long_ml.rds"))

TN1_umap <- run_umap(TN1_popseg_long_ml)

TN1_clustering <- run_clustering(TN1_umap,
                                 k_snn_major = 45,
                                 k_snn_minor = 17)

TN1_ordered <- order_dataset(popseg_long = TN1_popseg_long_ml,
                             clustering = TN1_clustering)

plot_umap(umap_df = TN1_umap,
          clustering = TN1_clustering)

TN1_consensus <- calculate_consensus(df = TN1_ordered$dataset_ordered,
                                     clusters = TN1_ordered$clustering_ordered$subclones)

TN1_gen_classes <- consensus_genomic_classes(TN1_consensus,
                                             ploidy_VAL = TN1_ploidy)

TN1_me_consensus_tree <- run_me_tree(consensus_df = TN1_consensus,
                                     clusters = TN1_clustering,
                                     ploidy_VAL = TN1_ploidy)

TN1_annotation_genes <- c("SHC1",
                          "RUVBL1",
                          "PIK3CA",
                          "FGFR4",
                          "CDKN1A",
                          "EGFR",
                          "FGFR1",
                          "MYC",
                          "CDKN2A",
                          "GATA3",
                          "PTEN",
                          "CDK4",
                          "MDM2",
                          "BRCA2",
                          "RB1",
                          "TP53",
                          "BRCA1",
                          "CCNE1",
                          "AURKA",
                          "CCND1")
```

```{r TN1_heatmap, cache = FALSE, fig.height=8}
plot_heatmap(df = TN1_ordered$dataset_ordered,
             ploidy_VAL = TN1_ploidy,
             ploidy_trunc = 2*(round(TN1_ploidy)),
             clusters = TN1_ordered$clustering_ordered,
             genomic_classes = TN1_gen_classes,
             keep_gene = TN1_annotation_genes,
             tree_order = TN1_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN1_consensus_ht, cache=FALSE}
plot_consensus_heatmap(df = TN1_consensus,
                       clusters = TN1_ordered$clustering_ordered,
                       ploidy_VAL = TN1_ploidy,
                       ploidy_trunc = 2*(round(TN1_ploidy)),
                       keep_gene = TN1_annotation_genes,
                       tree_order = TN1_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN1_gen_classes)
```

## TN2
```{r TN2}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN2_ploidy <- 3.03

TN2_popseg <- readRDS(here("extdata/popseg/TN2_popseg.rds"))

TN2_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN2_popseg_long_ml.rds"))

TN2_umap <- run_umap(TN2_popseg_long_ml)

TN2_clustering <- run_clustering(TN2_umap,
                                 k_snn_major = 63,
                                 k_snn_minor = 17)

TN2_ordered <- order_dataset(popseg_long = TN2_popseg_long_ml,
                             clustering = TN2_clustering)

plot_umap(umap_df = TN2_umap,
          clustering = TN2_clustering)

TN2_consensus <- calculate_consensus(df = TN2_ordered$dataset_ordered,
                                     clusters = TN2_ordered$clustering_ordered$subclones)

TN2_gen_classes <- consensus_genomic_classes(TN2_consensus,
                                             ploidy_VAL = TN2_ploidy)

TN2_me_consensus_tree <- run_me_tree(consensus_df = TN2_consensus,
                                     clusters = TN2_clustering,
                                     ploidy_VAL = TN2_ploidy)

TN2_annotation_genes <- c(
  "SHC1",
  "PIK3CA",
  "FGFR4",
  "CDKN1A",
  "EGFR",
  "MTDH",
  "MYC",
  "GATA3",
  "PTEN",
  "CCND1",
  "PGR",
  "CDK4",
  "MDM2",
  "LRP1B",
  "BRCA2",
  "TP53",
  "BRCA1",
  "BCL2",
  "CCNE1",
  "AURKA"
)
```

```{r TN2_heatmap, cache = FALSE, fig.height=8}
plot_heatmap(df = TN2_ordered$dataset_ordered,
             ploidy_VAL = TN2_ploidy,
             ploidy_trunc = 2*(round(TN2_ploidy)),
             clusters = TN2_ordered$clustering_ordered,
             genomic_classes = TN2_gen_classes,
             keep_gene = TN2_annotation_genes,
             tree_order = TN2_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN2_consensus_ht, cache=FALSE}
plot_consensus_heatmap(df = TN2_consensus,
                       clusters = TN2_ordered$clustering_ordered,
                       ploidy_VAL = TN2_ploidy,
                       ploidy_trunc = 2*(round(TN2_ploidy)),
                       keep_gene = TN2_annotation_genes,
                       tree_order = TN2_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN2_gen_classes)
```


## TN3
```{r TN3}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN3_ploidy <- 3.44

TN3_popseg <- readRDS(here("extdata/popseg/TN3_popseg.rds"))

TN3_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN3_popseg_long_ml.rds"))

TN3_umap <- run_umap(TN3_popseg_long_ml)

TN3_clustering <- run_clustering(TN3_umap,
                                 k_snn_major = 65,
                                 k_snn_minor = 17)

TN3_ordered <- order_dataset(popseg_long = TN3_popseg_long_ml,
                             clustering = TN3_clustering)

plot_umap(umap_df = TN3_umap,
          clustering = TN3_clustering)

TN3_consensus <- calculate_consensus(df = TN3_ordered$dataset_ordered,
                                     clusters = TN3_ordered$clustering_ordered$subclones)

TN3_gen_classes <- consensus_genomic_classes(TN3_consensus,
                                             ploidy_VAL = TN3_ploidy)

TN3_me_consensus_tree <- run_me_tree(consensus_df = TN3_consensus,
                                     clusters = TN3_clustering,
                                     ploidy_VAL = TN3_ploidy)

TN3_annotation_genes <-
  c(
    "CDKN2C",
    "SHC1",
    "PIK3CA",
    "FGFR4",
    "EGFR",
    "FGFR1",
    "MYC",
    "CDKN2A",
    "GATA3",
    "PTEN",
    "CCND1",
    "CDK4",
    "MDM2",
    "RB1",
    "TP53",
    "BRCA1",
    "BCL2",
    "CCNE1",
    "AURKA",
    "LRP1B"
  )
```

```{r TN3_heatmap, cache = FALSE, fig.height=8}
plot_heatmap(df = TN3_ordered$dataset_ordered,
             ploidy_VAL = TN3_ploidy,
             ploidy_trunc = 2*(round(TN3_ploidy)),
             clusters = TN3_ordered$clustering_ordered,
             genomic_classes = TN3_gen_classes,
             keep_gene = TN3_annotation_genes,
             tree_order = TN3_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN3_consensus_ht, cache=FALSE}
plot_consensus_heatmap(df = TN3_consensus,
                       clusters = TN3_ordered$clustering_ordered,
                       ploidy_VAL = TN3_ploidy,
                       ploidy_trunc = 2*(round(TN3_ploidy)),
                       keep_gene = TN3_annotation_genes,
                       tree_order = TN3_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN3_gen_classes)
```

## TN4
```{r TN4, warning=FALSE}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN4_ploidy <- 3.81

TN4_popseg <- readRDS(here("extdata/popseg/TN4_popseg.rds"))

TN4_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN4_popseg_long_ml.rds"))

TN4_umap <- run_umap(TN4_popseg_long_ml)

TN4_clustering <- run_clustering(TN4_umap,
                                 k_snn_major = 75,
                                 k_snn_minor = 17)

TN4_ordered <- order_dataset(popseg_long = TN4_popseg_long_ml,
                             clustering = TN4_clustering)

plot_umap(umap_df = TN4_umap,
          clustering = TN4_clustering)

TN4_consensus <- calculate_consensus(df = TN4_ordered$dataset_ordered,
                                     clusters = TN4_ordered$clustering_ordered$subclones)

TN4_gen_classes <- consensus_genomic_classes(TN4_consensus,
                                             ploidy_VAL = TN4_ploidy)

TN4_me_consensus_tree <- run_me_tree(consensus_df = TN4_consensus,
                                     clusters = TN4_clustering,
                                     ploidy_VAL = TN4_ploidy)


TN4_annotation_genes <-
  c(
    "CDKN2C",
    "SHC1",
    "PIK3CA",
    "CDKN1A",
    "ESR1",
    "EGFR",
    "MYC",
    "CDKN2A",
    "GATA3",
    "PTEN",
    "MDM2",
    "BRCA2",
    "RB1",
    "TP53",
    "BRCA1",
    "BCL2",
    "CCNE1",
    "NCOA3",
    "AURKA",
    "IGF1R",
    "NCOA1"
  )
```

```{r TN4_heatmap, cache = FALSE, fig.height=8, warning=FALSE}
plot_heatmap(df = TN4_ordered$dataset_ordered,
             ploidy_VAL = TN4_ploidy,
             ploidy_trunc = 2*(round(TN4_ploidy)),
             clusters = TN4_ordered$clustering_ordered,
             genomic_classes = TN4_gen_classes,
             keep_gene = TN4_annotation_genes,
             tree_order = TN4_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN4_consensus_ht, cache=FALSE, warning=FALSE}
plot_consensus_heatmap(df = TN4_consensus,
                       clusters = TN4_ordered$clustering_ordered,
                       ploidy_VAL = TN4_ploidy,
                       ploidy_trunc = 2*(round(TN4_ploidy)),
                       keep_gene = TN4_annotation_genes,
                       tree_order = TN4_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN4_gen_classes)
```

## TN5
```{r TN5, warning=FALSE}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN5_ploidy <- 2.65

TN5_popseg <- readRDS(here("extdata/popseg/TN5_popseg.rds"))

TN5_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN5_popseg_long_ml.rds"))

TN5_umap <- run_umap(TN5_popseg_long_ml)

TN5_clustering <- run_clustering(TN5_umap,
                                 k_snn_major = 41,
                                 k_snn_minor = 17)

TN5_ordered <- order_dataset(popseg_long = TN5_popseg_long_ml,
                             clustering = TN5_clustering)

plot_umap(umap_df = TN5_umap,
          clustering = TN5_clustering)

TN5_consensus <- calculate_consensus(df = TN5_ordered$dataset_ordered,
                                     clusters = TN5_ordered$clustering_ordered$subclones)

TN5_gen_classes <- consensus_genomic_classes(TN5_consensus,
                                             ploidy_VAL = TN5_ploidy)

TN5_me_consensus_tree <- run_me_tree(consensus_df = TN5_consensus,
                                     clusters = TN5_clustering,
                                     ploidy_VAL = TN5_ploidy,
                                     rotate_nodes = c(8,10,11))

TN5_annotation_genes <-
  c(
    "CDKN2C",
    "GADD45A",
    "SHC1",
    "PIK3CA",
    "FGFR4",
    "EGFR",
    "FGFR1",
    "MYC",
    "CDKN2A",
    "GATA3",
    "PTEN",
    "CCND1",
    "MDM2",
    "BRCA2",
    "RB1",
    "TP53",
    "BRCA1",
    "PPM1D",
    "CCNE1",
    "ERBB2",
    "ESR1"
  )
```

```{r TN5_heatmap, cache = FALSE, fig.height=8, warning=FALSE}
plot_heatmap(df = TN5_ordered$dataset_ordered,
             ploidy_VAL = TN5_ploidy,
             ploidy_trunc = 2*(round(TN5_ploidy)),
             clusters = TN5_ordered$clustering_ordered,
             genomic_classes = TN5_gen_classes,
             keep_gene = TN5_annotation_genes,
             tree_order = TN5_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN5_consensus_ht, cache=FALSE, warning=FALSE}
plot_consensus_heatmap(df = TN5_consensus,
                       clusters = TN5_ordered$clustering_ordered,
                       ploidy_VAL = TN5_ploidy,
                       ploidy_trunc = 2*(round(TN5_ploidy)),
                       keep_gene = TN5_annotation_genes,
                       tree_order = TN5_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN5_gen_classes)
```

## TN6
```{r TN6, warning=FALSE}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN6_ploidy <- 3.17

TN6_popseg <- readRDS(here("extdata/popseg/TN6_popseg.rds"))

TN6_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN6_popseg_long_ml.rds"))

TN6_umap <- run_umap(TN6_popseg_long_ml)

TN6_clustering <- run_clustering(TN6_umap,
                                 k_snn_major = 51,
                                 k_snn_minor = 17)

TN6_ordered <- order_dataset(popseg_long = TN6_popseg_long_ml,
                             clustering = TN6_clustering)

plot_umap(umap_df = TN6_umap,
          clustering = TN6_clustering)

TN6_consensus <- calculate_consensus(df = TN6_ordered$dataset_ordered,
                                     clusters = TN6_ordered$clustering_ordered$subclones)

TN6_gen_classes <- consensus_genomic_classes(TN6_consensus,
                                             ploidy_VAL = TN6_ploidy)

TN6_me_consensus_tree <- run_me_tree(consensus_df = TN6_consensus,
                                     clusters = TN6_clustering,
                                     ploidy_VAL = TN6_ploidy,
                                     rotate_nodes = c(17:20, 22, 29))

TN6_annotation_genes <-
  c(
    "CDKN2C",
    "SHC1",
    "RUVBL1",
    "PIK3CA",
    "CDKN1A",
    "EGFR",
    "FGFR1",
    "CDKN2A",
    "GATA3",
    "PTEN",
    "CDK4",
    "MDM2",
    "BRCA2",
    "RB1",
    "TP53",
    "BRCA1",
    "BCL2",
    "NCOA3",
    "AURKA",
    "GATA3",
    "PGR"
  )
```

```{r TN6_heatmap, cache = FALSE, fig.height=8, warning=FALSE}
plot_heatmap(df = TN6_ordered$dataset_ordered,
             ploidy_VAL = TN6_ploidy,
             ploidy_trunc = 2*(round(TN6_ploidy)),
             clusters = TN6_ordered$clustering_ordered,
             genomic_classes = TN6_gen_classes,
             keep_gene = TN6_annotation_genes,
             tree_order = TN6_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN6_consensus_ht, cache=FALSE, warning=FALSE}
plot_consensus_heatmap(df = TN6_consensus,
                       clusters = TN6_ordered$clustering_ordered,
                       ploidy_VAL = TN6_ploidy,
                       ploidy_trunc = 2*(round(TN6_ploidy)),
                       keep_gene = TN6_annotation_genes,
                       tree_order = TN6_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN6_gen_classes)
```

## TN7
```{r TN7, warning=FALSE}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN7_ploidy <- 3.15

TN7_popseg <- readRDS(here("extdata/popseg/TN7_popseg.rds"))

TN7_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN7_popseg_long_ml.rds"))

TN7_umap <- run_umap(TN7_popseg_long_ml)

TN7_clustering <- run_clustering(TN7_umap,
                                 k_snn_major = 35,
                                 k_snn_minor = 17)

TN7_ordered <- order_dataset(popseg_long = TN7_popseg_long_ml,
                             clustering = TN7_clustering)

plot_umap(umap_df = TN7_umap,
          clustering = TN7_clustering)

TN7_consensus <- calculate_consensus(df = TN7_ordered$dataset_ordered,
                                     clusters = TN7_ordered$clustering_ordered$subclones)

TN7_gen_classes <- consensus_genomic_classes(TN7_consensus,
                                             ploidy_VAL = TN7_ploidy)

TN7_me_consensus_tree <- run_me_tree(consensus_df = TN7_consensus,
                                     clusters = TN7_clustering,
                                     ploidy_VAL = TN7_ploidy,
                                     rotate_nodes = c(26, 27))

TN7_annotation_genes <-
  c(
    "CDKN2C",
    "SHC1",
    "RUVBL1",
    "PIK3CA",
    "CDKN1A",
    "EGFR",
    "FGFR1",
    "CDKN2A",
    "GATA3",
    "PTEN",
    "CDK4",
    "MDM2",
    "BRCA2",
    "RB1",
    "TP53",
    "BRCA1",
    "BCL2",
    "NCOA3",
    "AURKA",
    "GATA3",
    "PGR"
  )
```

```{r TN7_heatmap, cache = FALSE, fig.height=8, warning=FALSE}
plot_heatmap(df = TN7_ordered$dataset_ordered,
             ploidy_VAL = TN7_ploidy,
             ploidy_trunc = 2*(round(TN7_ploidy)),
             clusters = TN7_ordered$clustering_ordered,
             genomic_classes = TN7_gen_classes,
             keep_gene = TN7_annotation_genes,
             tree_order = TN7_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN7_consensus_ht, cache=FALSE, warning=FALSE}
plot_consensus_heatmap(df = TN7_consensus,
                       clusters = TN7_ordered$clustering_ordered,
                       ploidy_VAL = TN7_ploidy,
                       ploidy_trunc = 2*(round(TN7_ploidy)),
                       keep_gene = TN7_annotation_genes,
                       tree_order = TN7_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN7_gen_classes)
```

## TN8
```{r TN8, warning=FALSE}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:42 2020
# Tumors Heatmaps/Consensus/Trees
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tue Nov 24 17:13:47 2020

TN8_ploidy <- 3.95

TN8_popseg <- readRDS(here("extdata/popseg/TN8_popseg.rds"))

TN8_popseg_long_ml <- readRDS(here("extdata/merge_levels/TN8_popseg_long_ml.rds"))

TN8_umap <- run_umap(TN8_popseg_long_ml)

TN8_clustering <- run_clustering(TN8_umap,
                                 k_snn_major = 43,
                                 k_snn_minor = 17)

TN8_ordered <- order_dataset(popseg_long = TN8_popseg_long_ml,
                             clustering = TN8_clustering)

plot_umap(umap_df = TN8_umap,
          clustering = TN8_clustering)

TN8_consensus <- calculate_consensus(df = TN8_ordered$dataset_ordered,
                                     clusters = TN8_ordered$clustering_ordered$subclones)

TN8_gen_classes <- consensus_genomic_classes(TN8_consensus,
                                             ploidy_VAL = TN8_ploidy)

TN8_me_consensus_tree <- run_me_tree(consensus_df = TN8_consensus,
                                     clusters = TN8_clustering,
                                     ploidy_VAL = TN8_ploidy,
                                     rotate_nodes = c(17,18, 25, 29))

TN8_annotation_genes <-
  c(
    "CDKN2C",
    "SHC1",
    "ESR1",
    "MTDH",
    "MYC",
    "GATA3",
    "PTEN",
    "PGR",
    "MDM2",
    "BRCA2",
    "RB1",
    "BCL2",
    "NCOA3",
    "AURKA",
    "CHEK2"
  )
```

```{r TN8_heatmap, cache = FALSE, fig.height=8, warning=FALSE}
plot_heatmap(df = TN8_ordered$dataset_ordered,
             ploidy_VAL = TN8_ploidy,
             ploidy_trunc = 2*(round(TN8_ploidy)),
             clusters = TN8_ordered$clustering_ordered,
             genomic_classes = TN8_gen_classes,
             keep_gene = TN8_annotation_genes,
             tree_order = TN8_me_consensus_tree$cs_tree_order,
             show_legend = TRUE)
```

```{r TN8_consensus_ht, cache=FALSE, warning=FALSE}
plot_consensus_heatmap(df = TN8_consensus,
                       clusters = TN8_ordered$clustering_ordered,
                       ploidy_VAL = TN8_ploidy,
                       ploidy_trunc = 2*(round(TN8_ploidy)),
                       keep_gene = TN8_annotation_genes,
                       tree_order = TN8_me_consensus_tree$cs_tree_order,
                       plot_title = NULL,
                       genomic_classes = TN8_gen_classes)
```


## Clones barplot
```{r clones_barplot}
n_clones_tumors <- tibble(
  sample = rep(c(
    "TN1",
    "TN2",
    "TN3",
    "TN4",
    "TN5",
    "TN6",
    "TN7",
    "TN8"
  ),2),
  n_clones = c(
    length(unique(TN1_clustering$superclones)),
    length(unique(TN2_clustering$superclones)),
    length(unique(TN3_clustering$superclones)),
    length(unique(TN4_clustering$superclones)),
    length(unique(TN5_clustering$superclones)),
    length(unique(TN6_clustering$superclones)),
    length(unique(TN7_clustering$superclones)),
    length(unique(TN8_clustering$superclones)),
    length(unique(TN1_clustering$subclones)),
    length(unique(TN2_clustering$subclones)),
    length(unique(TN3_clustering$subclones)),
    length(unique(TN4_clustering$subclones)),
    length(unique(TN5_clustering$subclones)),
    length(unique(TN6_clustering$subclones)),
    length(unique(TN7_clustering$subclones)),
    length(unique(TN8_clustering$subclones))
  ),
  group = c(
    rep("superclones",8),
    rep("subclones", 8)
  )
) 

p_clones_tumors <- n_clones_tumors %>%
  ggplot() +
  geom_col(
    aes(
      x = sample,
      y = n_clones,
      fill = fct_relevel(group, c("superclones",
                                  "subclones"))
    ),
    position = "dodge"
  ) +
  theme_classic() +
  my_theme +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  scale_y_continuous(
    breaks = scales::pretty_breaks(n = 10),
    limits = c(0, 22),
    expand = c(0, 0)
  ) +
  paletteer::scale_fill_paletteer_d("yarrr::info") +
  xlab("") +
  ylab("number of clones")

p_clones_tumors
```

## Shannon diversity
```{r shannon_diversity, warning=FALSE}
shan <- function(data, indices) {
  data_ind <- data[indices]
  prop <- janitor::tabyl(data_ind) %>% pull(percent) 
  div <- -sum(prop*log(prop))
  return(div)
}

TN1_proportions <- janitor::tabyl(TN1_clustering$subclones) %>% pull(percent)
TN2_proportions <- janitor::tabyl(TN2_clustering$subclones) %>% pull(percent)
TN3_proportions <- janitor::tabyl(TN3_clustering$subclones) %>% pull(percent)
TN4_proportions <- janitor::tabyl(TN4_clustering$subclones) %>% pull(percent)
TN5_proportions <- janitor::tabyl(TN5_clustering$subclones) %>% pull(percent)
TN6_proportions <- janitor::tabyl(TN6_clustering$subclones) %>% pull(percent)
TN7_proportions <- janitor::tabyl(TN7_clustering$subclones) %>% pull(percent)
TN8_proportions <- janitor::tabyl(TN8_clustering$subclones) %>% pull(percent)

TN1_diver <- -sum(TN1_proportions*log(TN1_proportions))
TN2_diver <- -sum(TN2_proportions*log(TN2_proportions))
TN3_diver <- -sum(TN3_proportions*log(TN3_proportions))
TN4_diver <- -sum(TN4_proportions*log(TN4_proportions))
TN5_diver <- -sum(TN5_proportions*log(TN5_proportions))
TN6_diver <- -sum(TN6_proportions*log(TN6_proportions))
TN7_diver <- -sum(TN7_proportions*log(TN7_proportions))
TN8_diver <- -sum(TN8_proportions*log(TN8_proportions))

boot_TN1 <- boot::boot(TN1_clustering$subclones, statistic = shan,  R = 3000)
boot_TN1_ci <- boot::boot.ci(boot_TN1)

boot_TN2 <- boot::boot(TN2_clustering$subclones, statistic = shan,  R = 3000)
boot_TN2_ci <- boot::boot.ci(boot_TN2)

boot_TN3 <- boot::boot(TN3_clustering$subclones, statistic = shan,  R = 3000)
boot_TN3_ci <- boot::boot.ci(boot_TN3)

boot_TN4 <- boot::boot(TN4_clustering$subclones, statistic = shan,  R = 3000)
boot_TN4_ci <- boot::boot.ci(boot_TN4)

boot_TN5 <- boot::boot(TN5_clustering$subclones, statistic = shan,  R = 3000)
boot_TN5_ci <- boot::boot.ci(boot_TN5)

boot_TN6 <- boot::boot(TN6_clustering$subclones, statistic = shan,  R = 3000)
boot_TN6_ci <- boot::boot.ci(boot_TN6)

boot_TN7 <- boot::boot(TN7_clustering$subclones, statistic = shan,  R = 3000)
boot_TN7_ci <- boot::boot.ci(boot_TN7)

boot_TN8 <- boot::boot(TN8_clustering$subclones, statistic = shan,  R = 3000)
boot_TN8_ci <- boot::boot.ci(boot_TN8)


div_table <- tibble(
  sample = c("TN1",
             "TN2",
             "TN3",
             "TN4",
             "TN5",
             "TN6",
             "TN7",
             "TN8"),
  shannon_index = c(
    TN1_diver,
    TN2_diver,
    TN3_diver,
    TN4_diver,
    TN5_diver,
    TN6_diver,
    TN7_diver,
    TN8_diver
  ),
  lci = c(
    boot_TN1_ci$normal[2],
    boot_TN2_ci$normal[2],
    boot_TN3_ci$normal[2],
    boot_TN4_ci$normal[2],
    boot_TN5_ci$normal[2],
    boot_TN6_ci$normal[2],
    boot_TN7_ci$normal[2],
    boot_TN8_ci$normal[2]
  ),
  uci = c(
    boot_TN1_ci$normal[3],
    boot_TN2_ci$normal[3],
    boot_TN3_ci$normal[3],
    boot_TN4_ci$normal[3],
    boot_TN5_ci$normal[3],
    boot_TN6_ci$normal[3],
    boot_TN7_ci$normal[3],
    boot_TN8_ci$normal[3]
  )
)

# error bar = 95% confidence interval
p_tumors_diver <- div_table %>%
  ggplot() +
  geom_errorbar(aes(
    x = fct_reorder(sample, shannon_index),
    ymin = lci,
    ymax = uci
  ),
  width = .1,
  size = 2) +
  geom_point(aes(
    x = fct_reorder(sample, shannon_index),
    y = shannon_index,
    color = sample
  ), size = 4) +
  theme_classic() +
  my_theme +
  theme(legend.position = "none",
        axis.text.x = element_text(
          angle = 90,
          vjust = 0.5,
          hjust = 1
        )) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 12)) +
  scale_color_manual(values = c(rcartocolor::carto_pal(8, "Safe"))) +
  ylab("shannon diversity index") +
  xlab("")

p_tumors_diver
```

## Gains/Losses plot
```{r}


TN1_alt_perc <-
  gain_loss_percentage(consensus = TN1_consensus,
                       ploidy_VAL = TN1_ploidy,
                       sample = "TN1")

TN2_alt_perc <-
  gain_loss_percentage(consensus = TN2_consensus,
                       ploidy = TN2_ploidy,
                       sample = "TN2")

TN3_alt_perc <-
  gain_loss_percentage(consensus = TN3_consensus,
                       ploidy = TN3_ploidy,
                       sample = "TN3")

TN4_alt_perc <-
  gain_loss_percentage(consensus = TN4_consensus,
                       ploidy = TN4_ploidy,
                       sample = "TN4")

TN5_alt_perc <-
  gain_loss_percentage(consensus = TN5_consensus,
                       ploidy = TN5_ploidy,
                       sample = "TN5")

TN6_alt_perc <-
  gain_loss_percentage(consensus = TN6_consensus,
                       ploidy = TN6_ploidy,
                       sample = "TN6")

TN7_alt_perc <-
  gain_loss_percentage(consensus = TN7_consensus,
                       ploidy = TN7_ploidy,
                       sample = "TN7")

TN8_alt_perc <-
  gain_loss_percentage(consensus = TN8_consensus,
                       ploidy = TN8_ploidy,
                       sample = "TN8")


all_tumors_gainloss_percentage <- 
  bind_rows(TN2_alt_perc,
            TN3_alt_perc,
            TN4_alt_perc,
            TN1_alt_perc,
            TN5_alt_perc,
            TN6_alt_perc,
            TN7_alt_perc,
            TN8_alt_perc
            ) %>% 
  dplyr::rename(percent = n)

p_gain_loss <- ggplot() +
  geom_col(data = all_tumors_gainloss_percentage, 
           aes(x = fct_relevel(clone, rev(unique(gtools::mixedsort(all_tumors_gainloss_percentage$clone)))),
               y = percent,
               fill = class
           ),
           color = "black") +
  facet_wrap(vars(sample), ncol = 4, scales = "free_y") +
  scale_fill_manual(values = c("ground_state" = "white",
                               "gain" = "firebrick3",
                               "loss" = "steelblue"),
                    label = c("loss",
                              "neutral",
                              "gain"),
                    breaks = c("loss",
                               "ground_state",
                               "gain")) +
  theme_cowplot() +
    theme(strip.background = element_rect(fill = "white"),
        legend.title = element_blank(),
        legend.position = "top",
        axis.text = element_text(size = 10)) +
  coord_flip() +
  xlab("") 
  # ggtitle("Percentage of gain_loss per subclone")

p_gain_loss
```

## Genomic classes plots

### Counts

```{r gen_class_setup, warning=FALSE}
TN1_seg_length <- calc_genclass_length(TN1_gen_classes,
                                       popseg = TN1_popseg,
                                       popseg_long = TN1_popseg_long_ml) %>% 
  mutate(sample = "TN1")

TN2_seg_length <- calc_genclass_length(TN2_gen_classes,
                                       popseg = TN2_popseg,
                                       popseg_long = TN2_popseg_long_ml) %>% 
  mutate(sample = "TN2")

TN3_seg_length <- calc_genclass_length(TN3_gen_classes,
                                       popseg = TN3_popseg,
                                       popseg_long = TN3_popseg_long_ml) %>% 
  mutate(sample = "TN3")

TN4_seg_length <- calc_genclass_length(TN4_gen_classes,
                                       popseg = TN4_popseg,
                                       popseg_long = TN4_popseg_long_ml) %>% 
  mutate(sample = "TN4")

TN5_seg_length <- calc_genclass_length(TN5_gen_classes,
                                       popseg = TN5_popseg,
                                       popseg_long = TN5_popseg_long_ml) %>% 
  mutate(sample = "TN5")

TN6_seg_length <- calc_genclass_length(TN6_gen_classes,
                                       popseg = TN6_popseg,
                                       popseg_long = TN6_popseg_long_ml) %>% 
  mutate(sample = "TN6")

TN7_seg_length <- calc_genclass_length(TN7_gen_classes,
                                       popseg = TN7_popseg,
                                       popseg_long = TN7_popseg_long_ml) %>% 
  mutate(sample = "TN7")

TN8_seg_length <- calc_genclass_length(TN8_gen_classes,
                                       popseg = TN8_popseg,
                                       popseg_long = TN8_popseg_long_ml) %>% 
  mutate(sample = "TN8")

df_cna <- bind_rows(TN1_seg_length,
                    TN2_seg_length,
                    TN3_seg_length,
                    TN4_seg_length,
                    TN5_seg_length,
                    TN6_seg_length,
                    TN7_seg_length,
                    TN8_seg_length)

```

```{r gen_class_counts}
p_count_cna <- df_cna %>%
  dplyr::group_by(sample) %>%
  dplyr::distinct(seg_index, .keep_all = TRUE) %>% 
  dplyr::count(class) %>% 
  dplyr::mutate(class = fct_relevel(class,
                                    c("uCNA",
                                      "sCNA",
                                      "cCNA"))) %>%
  ggplot()  +
  geom_bar(
    aes(x =  sample,
        y = n,
        fill = class),
    position = "stack",
    stat = "identity",
    width = .6
  ) +
  scale_fill_manual(
    values = c(
      "cCNA" = "#414451",
      "sCNA" = "#A5ACAF",
      "uCNA" = "#FF800E"
    ),
    breaks = c("cCNA",
               "sCNA",
               "uCNA"),
    labels = c("cCNA",
               "sCNA",
               "uCNA")
  ) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 15),
                     expand = c(0, 0)) +
  theme_classic() +
  my_theme +
  theme(legend.position = 'top',
        axis.text.x = element_text(angle = 90,
                                   vjust = .5,
                                   hjust = 1),
        axis.text = element_text(color = 'black')) +
  xlab("") +
  ylab("CNA class count")

p_count_cna
```

### Segment length
```{r}
p_seg_box <- df_cna %>%
    dplyr::group_by(sample) %>%
  dplyr::distinct(seg_index, .keep_all = TRUE) %>% 
  dplyr::mutate(class = fct_relevel(class,
                                    c("cCNA",
                                      "sCNA",
                                      "uCNA"))) %>%
  ggplot() +
  geom_boxplot(
    aes(x = sample,
        y = seg_length,
        fill = class),
    outlier.shape = 21,
    outlier.alpha = .3
  ) +
  scale_fill_manual(
    values = c(
      "cCNA" = "#414451",
      "sCNA" = "#A5ACAF",
      "uCNA" = "#FF800E"
    ),
    breaks = c("cCNA",
               "sCNA",
               "uCNA"),
    labels = c("cCNA",
               "sCNA",
               "uCNA")
  ) +
  theme_classic() +
  my_theme +
  theme(axis.text = element_text(color = "black")) +
  scale_y_continuous(
    breaks = scales::pretty_breaks(n = 10),
    labels = scales::unit_format(unit = "",
                                 scale = 1e-6)
  ) +
  xlab("") +
  ylab("segment length (Mb)")

p_seg_box
```

